---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: file
  name: image
  label: image
  description: Project Thumbnail
- type: text
  name: description
  label: description
  description: meta description
