---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Blog Post
- type: directory
  path: exampleSite/content/english/blogs
  label: Post (en)
  create: documents
  match: "**/*"
  templates:
  - post
- type: directory
  path: exampleSite/content/french/blogs
  label: Post (fr)
  create: documents
  match: "**/*"
  templates:
  - post
- type: heading
  label: Author
- type: directory
  path: exampleSite/content/english/author
  label: Author (en)
  create: documents
  match: "**/*"
  templates:
  - author
- type: directory
  path: exampleSite/content/french/author
  label: Author (fr)
  create: documents
  match: "**/*"
  templates:
  - author
- type: heading
  label: Publications
- type: directory
  path: exampleSite/content/english/publications
  label: Publication (en)
  create: documents
  match: "**/*"
  templates:
  - publication
- type: directory
  path: exampleSite/content/french/publications
  label: Publication (fr)
  create: documents
  match: "**/*"
  templates:
  - publication
- type: heading
  label: Pojects
- type: directory
  path: exampleSite/content/english/projects
  label: Project (en)
  create: documents
  match: "**/*"
  templates:
  - project
- type: directory
  path: exampleSite/content/french/projects
  label: Projects (fr)
  create: documents
  match: "**/*"
- type: heading
  label: Talks
- type: directory
  path: exampleSite/content/english/talks
  label: Talk (en)
  create: documents
  match: "**/*"
  templates:
  - talk
- type: directory
  path: exampleSite/content/french/talks
  label: Talk (fr)
  create: documents
  match: "**/*"
  templates:
  - talk
- type: heading
  label: Other Pages
- type: directory
  path: exampleSite/content/english
  label: All Pages (en)
  create: all
  match: "**/*"
  templates:
  - new-page
- type: directory
  path: exampleSite/content/french
  label: All Pages (fr)
  create: all
  match: "**/*"
  templates:
  - new-page
- type: heading
  label: Data
- type: directory
  path: exampleSite/data/en
  label: Data (en)
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/data/fr
  label: Data (fr)
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/i18n
  label: i18n
  create: documents
  match: "**/*"
- type: heading
  label: Configuration
- type: directory
  path: exampleSite
  label: Configuration
  create: all
  match: "*.toml"
  new_doc_ext: toml
upload_dir: exampleSite/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.63.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.63.2
